In [1]:
import torch
torch.__version__

'2.5.1+cu124'

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.item()

7

In [ ]:
MATRIX= torch.tensor([[7,8],[9,10]])

In [ ]:
rand_tensor=torch.rand(size=(3,4))
rand_tensor, rand_tensor.dtype

(tensor([[0.4900, 0.1999, 0.2932, 0.2904],
         [0.4658, 0.1379, 0.0168, 0.6059],
         [0.8943, 0.6801, 0.8007, 0.6856]]),
 torch.float32)

In [ ]:
zero_to_ten = torch.range(0,10)
ztt = torch.arange(start=0,end=10,step=1)
ztt

<ipython-input-10-b7430dc69494>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten = torch.range(0,10)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### NN implementation

In [ ]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

In [ ]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2,out_features=6)

x = tensor_A
output = linear(x)
print(f"\nInput shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")


Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [2]:
x = torch.arange(12,dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [4]:
x.numel()

12

In [7]:
x.shape
X = x.reshape(3,4)

In [6]:
torch.tensor([[2,1,4,5],[1,2,3,4],[4,5,2,1]])

tensor([[2, 1, 4, 5],
        [1, 2, 3, 4],
        [4, 5, 2, 1]])

In [8]:
X[-1],X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [9]:
torch.exp(x)

tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
        4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04])

In [10]:
x = torch.tensor([1.0,2,4,8])
y= torch.tensor([2,2,2,2])

x+y,x-y,x*y,x/y,x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [13]:
X = torch.arange(12,dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])

torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

Broadcasting


In [14]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [15]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

Saving Memory


In [16]:
before = id(Y)
Y = Y+X
id(Y) == before

False

In [17]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X+Y
print('id(Z):', id(Z))

id(Z): 139237905051632
id(Z): 139237905051632


In [18]:
A =  X.numpy()
B = torch.from_numpy(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

### Data Preprocessing

In [21]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
dfile = os.path.join('..', 'data', 'house_tiny.csv')
with open(dfile, 'w') as f:
    f.write('''NumRooms,RoofType,Price
NA,NA,127500
2,NA,106000
4,Slate,178100
NA,NA,140000''')

In [22]:
import pandas as pd

data = pd.read_csv(dfile)
print(data)

   NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0    Slate  178100
3       NaN      NaN  140000
