In [1]:
import torch
torch.__version__

'2.5.1+cu124'

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.item()

7

In [5]:
MATRIX= torch.tensor([[7,8],[9,10]])

In [8]:
rand_tensor=torch.rand(size=(3,4))
rand_tensor, rand_tensor.dtype

(tensor([[0.4900, 0.1999, 0.2932, 0.2904],
         [0.4658, 0.1379, 0.0168, 0.6059],
         [0.8943, 0.6801, 0.8007, 0.6856]]),
 torch.float32)

In [10]:
zero_to_ten = torch.range(0,10)
ztt = torch.arange(start=0,end=10,step=1)
ztt

<ipython-input-10-b7430dc69494>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten = torch.range(0,10)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### NN implementation

In [11]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

In [12]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2,out_features=6)

x = tensor_A
output = linear(x)
print(f"\nInput shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")


Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])
